# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Worn Out Bible"
description: > # this means to ignore newlines until "email:"
   Andrew Stacy's Bible Study Blog

email: ajstacy@gmail.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Andrew Stacy'
author: 'Andrew Stacy'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://wornoutbible.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@ajstacy06'

#fill in disqus shortname to use disqus
disqus: wornoutbible

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ajstacy06
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/AJStacy
    desc:	Find my code at github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
